name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'  # Cache yarn dependencies

    - name: Install Yarn
      run: npm install -g yarn  # Install yarn globally if not pre-installed

    - name: Install dependencies
      run: yarn install  # Install dependencies using Yarn

    - name: Build
      run: yarn build --if-present  # Build the project

    - name: Run tests
      run: yarn test  # Run tests using Yarn
      
